"""Seed catalog of standard tracked items (Part 91 defaults).

IMPORTANT: every interval here is an ADVISORY DEFAULT for convenience. Real
intervals depend on the specific aircraft make/model, equipment manufacturer,
ICAs, applicable Airworthiness Directives, and type of operation, and must be
confirmed by qualified maintenance personnel. All values are editable per
aircraft once an item is created.
"""

# Each entry maps to an ItemType row.
CATALOG = [
    # --- Regulatory calendar inspections ------------------------------------
    dict(
        name="Annual inspection",
        category="inspection",
        reg_reference="91.409(a)",
        interval_kind="calendar",
        default_interval_months=12,
        applies_to_component_type="airframe",
        is_required_for_airworthiness=True,
        description="Annual inspection of the airframe and powerplant.",
    ),
    dict(
        name="Transponder check",
        category="avionics",
        reg_reference="91.413",
        interval_kind="calendar",
        default_interval_months=24,
        applies_to_component_type="airframe",
        is_required_for_airworthiness=True,
        description="Transponder test and inspection (24 calendar months).",
    ),
    dict(
        name="Altimeter / pitot-static system check",
        category="avionics",
        reg_reference="91.411",
        interval_kind="calendar",
        default_interval_months=24,
        applies_to_component_type="airframe",
        is_required_for_airworthiness=True,
        description="Altimeter and static pressure system test (IFR; 24 cal months).",
    ),
    dict(
        name="ELT inspection",
        category="emergency_equipment",
        reg_reference="91.207(d)",
        interval_kind="calendar",
        default_interval_months=12,
        applies_to_component_type="airframe",
        is_required_for_airworthiness=True,
        description="Emergency Locator Transmitter inspection (12 calendar months).",
    ),
    dict(
        name="ELT battery replacement",
        category="emergency_equipment",
        reg_reference="91.207(c)",
        interval_kind="fixed",
        applies_to_component_type="airframe",
        is_required_for_airworthiness=True,
        description="Replace by battery expiry date, or after 1 hr cumulative "
        "use / half useful life. Set the expiry date when installed.",
    ),
    dict(
        name="Aircraft registration",
        category="registration",
        reg_reference="14 CFR 47",
        interval_kind="fixed",
        applies_to_component_type="airframe",
        is_required_for_airworthiness=True,
        description="FAA certificate of registration; set its printed expiry date.",
    ),
    # --- Emergency / survival equipment -------------------------------------
    dict(
        name="Fire extinguisher inspection",
        category="emergency_equipment",
        interval_kind="calendar",
        default_interval_months=12,
        applies_to_component_type="airframe",
        description="Annual fire extinguisher inspection.",
    ),
    dict(
        name="Fire extinguisher hydrostatic test",
        category="emergency_equipment",
        interval_kind="calendar",
        default_interval_months=60,
        applies_to_component_type="airframe",
        description="Periodic hydrostatic test (interval varies 5-12 yr by type).",
    ),
    dict(
        name="First aid / medical kit",
        category="emergency_equipment",
        interval_kind="fixed",
        applies_to_component_type="airframe",
        description="Track the earliest content expiry date in the kit.",
    ),
    dict(
        name="Life vests inspection",
        category="emergency_equipment",
        interval_kind="calendar",
        default_interval_months=12,
        applies_to_component_type="airframe",
        description="Life preserver inspection (per manufacturer; CO2 cylinder life).",
    ),
    dict(
        name="Life raft repack / recertification",
        category="emergency_equipment",
        interval_kind="calendar",
        default_interval_months=12,
        applies_to_component_type="airframe",
        description="Life raft inspection and repack (1-5 yr per manufacturer).",
    ),
    dict(
        name="Flares / pyrotechnic signals",
        category="emergency_equipment",
        interval_kind="fixed",
        applies_to_component_type="airframe",
        description="Replace at printed expiry (~36 months from manufacture).",
    ),
    dict(
        name="Portable oxygen bottle hydrostatic test",
        category="emergency_equipment",
        interval_kind="calendar",
        default_interval_months=60,
        applies_to_component_type="airframe",
        description="DOT cylinder hydrostatic test (3 or 5 yr by cylinder spec).",
    ),
    # --- Hours / combo maintenance ------------------------------------------
    dict(
        name="Oil & filter change",
        category="engine",
        interval_kind="combo_first",
        default_interval_hours=50,
        default_interval_months=4,
        applies_to_component_type="engine",
        description="Oil and filter change (50 hours or 4 months, whichever first).",
    ),
    dict(
        name="100-hour inspection",
        category="inspection",
        reg_reference="91.409(b)",
        interval_kind="hours",
        default_interval_hours=100,
        applies_to_component_type="airframe",
        description="Required when carrying persons for hire / flight instruction.",
    ),
    dict(
        name="Magneto inspection",
        category="engine",
        interval_kind="hours",
        default_interval_hours=500,
        applies_to_component_type="engine",
        description="Magneto inspection / overhaul (per manufacturer).",
    ),
    dict(
        name="Spark plug service",
        category="engine",
        interval_kind="hours",
        default_interval_hours=100,
        applies_to_component_type="engine",
        description="Clean, gap and rotate spark plugs.",
    ),
    dict(
        name="Engine overhaul (TBO)",
        category="engine",
        interval_kind="combo_first",
        default_interval_hours=2000,
        default_interval_months=144,
        applies_to_component_type="engine",
        default_warning_days=180,
        description="Time/calendar between overhaul (manufacturer recommended).",
    ),
    dict(
        name="Propeller overhaul",
        category="propeller",
        interval_kind="combo_first",
        default_interval_hours=2000,
        default_interval_months=72,
        applies_to_component_type="propeller",
        default_warning_days=180,
        description="Propeller overhaul (hours and/or calendar per manufacturer).",
    ),
    dict(
        name="Vacuum pump replacement",
        category="airframe",
        interval_kind="hours",
        default_interval_hours=500,
        applies_to_component_type="airframe",
        description="Vacuum pump replacement (on condition / hours).",
    ),
    # --- Warbird / vintage powerplant ---------------------------------------
    dict(
        name="Condition inspection (annual)",
        category="inspection",
        reg_reference="Op Limitations",
        interval_kind="calendar",
        default_interval_months=12,
        applies_to_component_type="airframe",
        is_required_for_airworthiness=True,
        description="Annual condition inspection for Limited/Experimental-Exhibition "
        "warbirds, per the aircraft's operating limitations.",
    ),
    dict(
        name="Cylinder compression check",
        category="engine",
        interval_kind="calendar",
        default_interval_months=12,
        applies_to_component_type="engine",
        description="Differential compression check (radial/piston engines).",
    ),
    dict(
        name="Engine top overhaul",
        category="engine",
        interval_kind="hours",
        default_interval_hours=800,
        applies_to_component_type="engine",
        default_warning_days=120,
        description="Cylinder top overhaul on radial engines (manufacturer/operator).",
    ),
    dict(
        name="Coolant system inspection",
        category="engine",
        interval_kind="calendar",
        default_interval_months=12,
        applies_to_component_type="engine",
        description="Coolant/glycol system inspection (liquid-cooled inline engines).",
    ),
    # --- Amphibian / flying boat --------------------------------------------
    dict(
        name="Hull / float inspection",
        category="airframe",
        interval_kind="calendar",
        default_interval_months=12,
        applies_to_component_type="airframe",
        description="Hull and float watertight integrity inspection (amphibian).",
    ),
    dict(
        name="Landing gear retraction inspection",
        category="airframe",
        interval_kind="calendar",
        default_interval_months=12,
        applies_to_component_type="airframe",
        description="Retraction/operational check of amphibious landing gear.",
    ),
    # --- Helicopter: drivetrain & rotor (time-life components) ----------------
    dict(
        name="Hot section inspection",
        category="engine",
        interval_kind="hours",
        default_interval_hours=1000,
        applies_to_component_type="engine",
        default_warning_days=90,
        description="Turbine engine hot section inspection (e.g. T53).",
    ),
    dict(
        name="Main transmission overhaul",
        category="transmission",
        interval_kind="hours",
        default_interval_hours=2500,
        applies_to_component_type="transmission",
        default_warning_days=180,
        is_required_for_airworthiness=True,
        description="Main rotor transmission overhaul (TBO).",
    ),
    dict(
        name="Main rotor blade retirement",
        category="rotor",
        interval_kind="combo_first",
        default_interval_hours=2500,
        default_interval_cycles=11000,
        applies_to_component_type="main_rotor",
        default_warning_days=180,
        is_required_for_airworthiness=True,
        description="Life-limited main rotor blade retirement (hours/cycles).",
    ),
    dict(
        name="Main rotor hub & grip inspection",
        category="rotor",
        interval_kind="hours",
        default_interval_hours=600,
        applies_to_component_type="main_rotor",
        is_required_for_airworthiness=True,
        description="Main rotor hub, grips and pillow blocks inspection.",
    ),
    dict(
        name="Tail rotor blade retirement",
        category="rotor",
        interval_kind="hours",
        default_interval_hours=2500,
        applies_to_component_type="tail_rotor",
        default_warning_days=120,
        is_required_for_airworthiness=True,
        description="Life-limited tail rotor blade retirement.",
    ),
    dict(
        name="42° / intermediate gearbox overhaul",
        category="transmission",
        interval_kind="hours",
        default_interval_hours=2500,
        applies_to_component_type="gearbox",
        default_warning_days=120,
        description="Intermediate (42°) gearbox overhaul.",
    ),
    dict(
        name="90° / tail rotor gearbox overhaul",
        category="transmission",
        interval_kind="hours",
        default_interval_hours=2500,
        applies_to_component_type="gearbox",
        default_warning_days=120,
        description="Tail rotor (90°) gearbox overhaul.",
    ),
    dict(
        name="Hydraulic system inspection",
        category="airframe",
        interval_kind="hours",
        default_interval_hours=300,
        applies_to_component_type="airframe",
        description="Hydraulic servo/system inspection (helicopter).",
    ),
]
